name: Github Actions Demo
on: [push]
jobs: 
  Check-Github-Actions:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          repository: 'vikingute/lego-bricks'
      - name: 当前仓库列表文件
        run: ls ${{ github.workspace }}
      - uses: actions/setup-node@v2
        with: 
          node-version: '16'
      - run: node -v
      - run: npm i -g typescript
      - run: tsc -v
