name: Github Actions Demo
on: [push]
jobs: 
  Check-Github-Actions:
    runs-on: ubuntu-latest
    steps: 
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
